// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: bridge_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// First message in the stream must be of SendFileRequest type
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to FileInfo:
	//
	//	*File_Request
	//	*File_Chunk
	FileInfo isFile_FileInfo `protobuf_oneof:"fileInfo"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{0}
}

func (m *File) GetFileInfo() isFile_FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

func (x *File) GetRequest() *SendFileRequest {
	if x, ok := x.GetFileInfo().(*File_Request); ok {
		return x.Request
	}
	return nil
}

func (x *File) GetChunk() *FileChunk {
	if x, ok := x.GetFileInfo().(*File_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isFile_FileInfo interface {
	isFile_FileInfo()
}

type File_Request struct {
	Request *SendFileRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type File_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*File_Request) isFile_FileInfo() {}

func (*File_Chunk) isFile_FileInfo() {}

var File_bridge_service_proto protoreflect.FileDescriptor

var file_bridge_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x42, 0x0a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x4e, 0x0a,
	0x1c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a,
	0x0a, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x28, 0x01, 0x42, 0x66, 0x0a,
	0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x69, 0x67, 0x6b, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x42, 0x69, 0x67, 0x2d, 0x4b, 0x6f, 0x74, 0x69, 0x6b, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bridge_service_proto_rawDescOnce sync.Once
	file_bridge_service_proto_rawDescData = file_bridge_service_proto_rawDesc
)

func file_bridge_service_proto_rawDescGZIP() []byte {
	file_bridge_service_proto_rawDescOnce.Do(func() {
		file_bridge_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridge_service_proto_rawDescData)
	})
	return file_bridge_service_proto_rawDescData
}

var file_bridge_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bridge_service_proto_goTypes = []interface{}{
	(*File)(nil),            // 0: proto.File
	(*SendFileRequest)(nil), // 1: proto.SendFileRequest
	(*FileChunk)(nil),       // 2: proto.FileChunk
	(*FileStatus)(nil),      // 3: proto.FileStatus
}
var file_bridge_service_proto_depIdxs = []int32{
	1, // 0: proto.File.request:type_name -> proto.SendFileRequest
	2, // 1: proto.File.chunk:type_name -> proto.FileChunk
	0, // 2: proto.TransparentDataBridgeService.SendChunks:input_type -> proto.File
	3, // 3: proto.TransparentDataBridgeService.SendChunks:output_type -> proto.FileStatus
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bridge_service_proto_init() }
func file_bridge_service_proto_init() {
	if File_bridge_service_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bridge_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bridge_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*File_Request)(nil),
		(*File_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridge_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_service_proto_goTypes,
		DependencyIndexes: file_bridge_service_proto_depIdxs,
		MessageInfos:      file_bridge_service_proto_msgTypes,
	}.Build()
	File_bridge_service_proto = out.File
	file_bridge_service_proto_rawDesc = nil
	file_bridge_service_proto_goTypes = nil
	file_bridge_service_proto_depIdxs = nil
}
